### PR TITLE
Python 3.11 compatibility

### PR DESCRIPTION
**Pull request by dotlambda**
`@asyncio.coroutine` was removed in Python 3.11.

### CODE REVIEW

**Comment by balloob** [comment]
@aequitas would you be able to take a look at this PR? It's preventing it from running under Python 3.11

**Comment by aequitas** [comment]
@dotlambda I rebased your PR and pushed a commit to fix CI, should be good te merge now. Sorry for the delay.

**Review by aequitas — APPROVED** [review]

**Comment by aequitas** [comment]
https://github.com/aequitas/python-rflink/releases/tag/0.0.65

**Comment by javicalle** [comment]
Thanks Johan!

**Pull request merged**
