### PR TITLE
TCP KEEPALIVE support

### PR DESCRIPTION
**Pull request by cpainchaud**
python-rflink>python -m rflink --host=192.168.0.31 --port=1900 -vv --keepalive --keepidle=3 --keepinterval=3 --keepcount=3
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:rflink.protocol:connected
DEBUG:rflink.protocol:applying TCP KEEPALIVE settings: IDLE=3/INTVL=3/CNT=3
ERROR:rflink.protocol:disconnected due to exception

### CODE REVIEW

**Comment by aequitas** [comment]
Strange, still doesn't seem to trigger, I changed the base back to master, as it will only trigger on that branch. Maybe it doesn't trigger if you change base, only when the PR is created/updated?

**Comment by cpainchaud** [comment]
I cant tell :D

**Comment by cpainchaud** [comment]
so whats next step? :)

**Comment by aequitas** [comment]
let me check

**Comment by aequitas** [comment]
Seems to be working now :)

**Review by aequitas — DISMISSED** [review]

**Comment by cpainchaud** [comment]
@aequitas  almost there! Python 3.8 has more complaints which I just addressed but CI is stuck again?

**Comment by aequitas** [comment]
Looks like your branch is not based on the latest master: https://github.com/aequitas/python-rflink/network

**Comment by cpainchaud** [comment]
> Looks like your branch is not based on the latest master: https://github.com/aequitas/python-rflink/network

yeah you did some commits in the meantime, I have rebased the code and it should be fine now !

**Comment by aequitas** [comment]
The python 3.8 tests also contain type checking and linting besides testing, that's why it's failing. Seems some types are not in order. It's hard to see because the test output is collapse.

**Comment by cpainchaud** [comment]
Can you make sense of these errors ?

  typing run-test: commands[0] | mypy --strict --ignore-missing-imports rflink
  rflink/protocol.py:76: error: Incompatible types in assignment (expression has type "Optional[Any]", variable has type "bool")
  rflink/protocol.py:79: error: Incompatible types in assignment (expression has type "Optional[Any]", variable has type "int")
  rflink/protocol.py:82: error: Incompatible types in assignment (expression has type "Optional[Any]", variable has type "int")
  rflink/protocol.py:85: error: Incompatible types in assignment (expression has type "Optional[Any]", variable has type "int")
  Found 4 errors in 1 file (checked 4 source files)

When I look at my code, i dont see the problem

**Comment by cpainchaud** [comment]
@aequitas I was able to fix types  by forcing an ignore but I am afraid I just cannot understand the last issue, it doesn't tell whats wrong (unless there another place to know!?)

tox: lint
  lint run-test-pre: PYTHONHASHSEED='1881499320'
  lint run-test: commands[0] | pylama setup.py rflink rflinkproxy tests
  lint run-test: commands[1] | black --check .
  would reformat /home/runner/work/python-rflink/python-rflink/rflink/__main__.py
  would reformat /home/runner/work/python-rflink/python-rflink/rflink/protocol.py
  Oh no! 💥 💔 💥
  2 files would be reformatted, 10 files would be left unchanged.
  ERROR: InvocationError for command /home/runner/work/python-rflink/python-rflink/.tox/lint/bin/black --check . (exited with code 1)

**Comment by cpainchaud** [comment]
@aequitas tell me it's fine this time!!! I learned many things just for this project :D Tox, Black, Async IO....... a training course by itself

Can I suggest that you edit tox.ini to enable Black's --diff  ?

**Comment by aequitas** [comment]
Maybe we should rethink that kwargs construct as a whole. As it's quiet a construct for something that should be simple. Also is it necessary to make all the keep alive arguments configurable? Could we go with just an enable and use some sane defaults? I hate to comment on your PR like this after the work you put it in, but I see the amount of code added getting quiet large.

Adding the `--diff` to black for the check would make sense indeed. It's not documented but running `tox -e fix` will auto fix issues like formatting and import sorting.

**Comment by cpainchaud** [comment]
unfortunately default Keepalive is 2 hours which is pointless so it takes a minimum of 2 arguments or I could merge 2 in one : None ) disabled, integer means the timeout value. Then as you suggest we could use sane defaults for probes interval and count. 

The whole feature is turned off by default so it won't impact existing devs

**Comment by aequitas** [comment]
Just make the defaults that fit for you and make it a single bool flag to
enable keep alive. If someone needs customization we can add more flags and
the complexity of the kwargs parsing then.

Op di 9 feb. 2021 om 21:42 schreef Christophe Painchaud <
notifications@github.com>

**Comment by cpainchaud** [comment]
I didnt realize I could implement arguments directly, I thought the factory was limiting me to base class ! Anyways I am making the change you requested

**Comment by cpainchaud** [comment]
here we go !!! 1 single argument, no more kwargs

**Review by aequitas — APPROVED** [review]

**Comment by aequitas** [comment]
I create a new tag (https://github.com/aequitas/python-rflink/releases/tag/0.0.57), it should soon be build into a release and pushed to pypi by CI.

**Comment by cpainchaud** [comment]
it looks like PyPi automated push is broken as well :p 24 hours and nothing it's usually a few hours maximum

thank you

**Comment by aequitas** [comment]
should be running now: https://github.com/aequitas/python-rflink/actions/runs/557232073

**Comment by cpainchaud** [comment]
all fine now, thank you!

**Pull request merged**
