### PR TITLE
Enable TCP_KEEPALIVE on demand

### PR DESCRIPTION
**Pull request by cpainchaud**
from issue #54 

python-rflink>python -m rflink --host=192.168.0.31 --port=1900 -vv --keepalive --keepidle=3 --keepinterval=3 --keepcount=3
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:rflink.protocol:connected
DEBUG:rflink.protocol:applying TCP KEEPALIVE settings: IDLE=3/INTVL=3/CNT=3
ERROR:rflink.protocol:disconnected due to exception

### CODE REVIEW

**Comment by aequitas** [comment]
seems the CI didn't run on the PR. Don't know if its because of Github Actions issues still? It should run on every push. https://github.com/aequitas/python-rflink/blob/master/.github/workflows/push.yml#L3

Would you please look into fixing the issues https://github.com/aequitas/python-rflink/actions/runs/551712685 then I'll make sure the checks run again for PR's.

**Comment by cpainchaud** [comment]
i tried a new PR, i didnt see CI trigger

**Comment by aequitas** [comment]
probably due to https://github.com/WordPress/gutenberg/issues/17324

I updated the CI config, if you can rebase onto the test branch https://github.com/aequitas/python-rflink/tree/test it should work.

**Comment by cpainchaud** [comment]
ok, rebased to test branch

**Pull request merged**
